name: Build LG webOS App
on: [push, workflow_dispatch]

jobs:
  build_job:
    runs-on: ubuntu-latest
    # استخدام حاوية (Container) تحتوي على أدوات LG جاهزة
    container:
      image: node:18-bullseye

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Application
        run: |
          # تثبيت الأدوات داخل الحاوية بشكل نظيف
          npm install -g @lg-webos/ares-cli --unsafe-perm
          
          mkdir -p output
          # البحث عن مكان ملف appinfo.json
          APP_DIR=$(find . -name "appinfo.json" -exec dirname {} \; | head -n 1)
          
          # تنفيذ عملية البناء
          ares-package "$APP_DIR" -o ./output
          
      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: Movie-App-Package
          path: output/*.ipk
