name: Build LG webOS App
on: [push, workflow_dispatch]

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Application
        run: |
          mkdir -p output
          # استخدام الحزمة العامة المستقرة مباشرة
          APP_DIR=$(find . -name "appinfo.json" -exec dirname {} \; | head -n 1)
          npx ares-cli ares-package "$APP_DIR" -o ./output
          
      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: Movie-App-Package
          path: output/*.ipk
