name: Build LG webOS App
on: 
  push:
    branches:
      - main
  workflow_dispatch: # يتيح لك تشغيل البناء يدوياً

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install webOS CLI Tools
        run: |
          npm install -g @lg-webos/ares-cli

      - name: Package the Application
        run: |
          mkdir output
          ares-package . -o ./output

      - name: Upload Finished App
        uses: actions/upload-artifact@v4
        with:
          name: LG-TV-App-Package
          path: ./output/*.ipk
